# Generated by Django 5.2.3 on 2025-06-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_herosection_subtitle_remove_herosection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobutton',
            name='button_type',
            field=models.CharField(choices=[('dropdown', 'Menú Desplegable'), ('link', 'Enlace Simple')], default='link', max_length=10, verbose_name='Tipo de Botón'),
        ),
        migrations.CreateModel(
            name='HeroDropdownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_items', to='home.herobutton')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
