# Generated by Django 5.2.3 on 2025-06-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_herobutton_button_type_herodropdownitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='name',
            field=models.CharField(default='CUBATRAM', max_length=50),
            preserve_default=False,
        ),
    ]
