# Generated by Django 5.2.3 on 2025-06-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_herosection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='footer_logo',
        ),
    ]
