# Generated by Django 5.2.3 on 2025-06-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_contactinfo_footer_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='icon',
        ),
    ]
