# Generated by Django 5.2.3 on 2025-06-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_socialmedialink_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobutton',
            name='button_type',
            field=models.CharField(choices=[('destination', 'Destination'), ('category', 'Category'), ('link', 'Enlace Simple')], default='link', max_length=12, verbose_name='Tipo de Botón'),
        ),
        migrations.DeleteModel(
            name='HeroDropdownItem',
        ),
    ]
