# Generated by Django 5.2.3 on 2025-06-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_herobutton_button_type_delete_herodropdownitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/categories/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='media/destinations/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(upload_to='media/hero/'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(upload_to='media/special_offers/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='main_image',
            field=models.ImageField(upload_to='media/tours/'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='media/tour_images/'),
        ),
    ]
