# Generated by Django 5.2.3 on 2025-06-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_category_image_alter_destination_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='title1',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosection',
            name='title2',
            field=models.CharField(default='test2', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosection',
            name='title3',
            field=models.CharField(default='test3', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/categories/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='static/media/destinations/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(upload_to='static/media/hero/'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(upload_to='static/media/special_offers/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='main_image',
            field=models.ImageField(upload_to='static/media/tours/'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='static/media/tour_images/'),
        ),
        migrations.DeleteModel(
            name='HeroButton',
        ),
    ]
